// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("solarwindsentity")
	ScopeName = "github.com/solarwinds/solarwinds-otel-collector-releases/connector/solarwindsentityconnector"
)

const (
	MetricsToLogsStability = component.StabilityLevelDevelopment
	LogsToLogsStability    = component.StabilityLevelDevelopment
)
