receivers:
  rabbitmq:
    endpoint: # Required parameter
    collection_interval: # Required parameter
    username: # Required secret
    password: # Required secret
    metrics:
      rabbitmq.message.delivered:
        enabled: true
      rabbitmq.message.published:
        enabled: true
      rabbitmq.message.acknowledged:
        enabled: true
      rabbitmq.message.dropped:
        enabled: true
      rabbitmq.consumer.count:
        enabled: true
      rabbitmq.message.current:
        enabled: true
  prometheus/rabbitmq:
    config:
      scrape_configs:
        - job_name: 'rabbitmq'
          scrape_interval: # Required parameter
          static_configs:
            - targets: # Required parameter
  # Optional receiver
  # filelog:
  #   include: # Required parameter
  #   start_at: end
  #   poll_interval: 5s

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30
  resource/rabbitmq:
    attributes:
      - key: sw.otelcol.receiver.name
        value: "rabbitmq"
        action: insert
      - key: sw.otelcol.integration.id
        value: # Required parameter
        action: insert
  resourcedetection/ec2:
    detectors: ["ec2"]
    timeout: 2s
    override: true
  resourcedetection/azure:
    detectors: ["azure"]
    timeout: 2s
    override: true
  resourcedetection/gcp:
    detectors: ["gcp"]
    timeout: 2s
    override: true
  resourcedetection/system:
    detectors: ["system"]
    timeout: 2s
    override: false
    system:
      hostname_sources: ["os"]
  batch:
    send_batch_max_size: 20000

extensions:
  solarwinds:
    token: # Required secret
    collector_name: # Required parameter
    data_center: # Required parameter

exporters:
  solarwinds:

service:
  extensions:
    - solarwinds
  pipelines:
    metrics/rabbitmq:
      receivers:
        - rabbitmq
        - prometheus/rabbitmq
      processors:
        - memory_limiter
        - resource/rabbitmq
        - resourcedetection/ec2
        - resourcedetection/azure
        - resourcedetection/gcp
        - resourcedetection/system
        - batch
      exporters:
        - solarwinds

    # Optional pipeline
    # logs/rabbitmq:
    #   receivers:
    #     - filelog
    #   processors:
    #     - memory_limiter
    #     - resource/rabbitmq
    #     - resourcedetection/ec2
    #     - resourcedetection/azure
    #     - resourcedetection/gcp
    #     - resourcedetection/system
    #     - batch
    #   exporters:
    #     - solarwinds
