receivers:
  nop:

extensions:
  solarwinds:
    collector_name: # Required parameter
    grpc: &grpc_settings
      endpoint: # Required parameter
      tls:
        insecure: false
      headers: {"Authorization": "Bearer ${env:SOLARWINDS_TOKEN}", "swi-reporter": "otel solarwinds-otel-collector"}

exporters:
  otlp_grpc:
    <<: *grpc_settings

service:
  extensions:
    - solarwinds
  pipelines:
    metrics:
      receivers:
        - nop
      exporters:
        - otlp_grpc
