// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("swok8sobjects")
	ScopeName = "github.com/solarwinds/solarwinds-otel-collector-releases/receiver/swok8sobjectsreceiver"
)

const (
	LogsStability = component.StabilityLevelBeta
)
