receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

extensions:
  solarwinds:
    token: ZQGVnShdGXJPosEk4-m36GPDTf1MYPCHinc8TbgONshXnpol9OqEDWqpn4XkFOGpK-vuczU
    collector_name: DEMO-TEST
    endpoint_url_override: otel.collector.na-01.dev-ssp.solarwinds.com:443
    without_entity: false
  # db_storage:
  #   driver: "sqlite"
  #   datasource: "file:./data/foo.db"


exporters:
  solarwinds:
  debug:
  file:
    path: result.log

connectors:
  solarwindsentity:
    source_prefix: "source."
    destination_prefix: "dest."
    schema:
      entities:
        - entity: KubernetesNamespace
          id:
            - k8s.namespace.name
            - sw.k8s.cluster.uid
          attributes:
        - entity: KubernetesCluster
          attributes:
            - k8s.cluster.name
          id:
            - sw.k8s.cluster.uid
        - entity: KubernetesPod
          id:
            - k8s.pod.name
            - sw.k8s.cluster.uid
          attributes:
            - k8s.namespace.name
      events:
        entities:
          - context: log
            type: KubernetesPod
            conditions:
          - context: log
            type: KubernetesCluster
            conditions:
          - context: log
            type: KubernetesNamespace
            conditions:
        relationships:
          - context: metricssdfs
            conditions: 
              - metric.name == "k8s.tcp.bytes"
            type: Contains
            source_entity: KubernetesPod
            destination_entity: KubernetesPod
            attributes:
          - context: log
            conditions:
              - attributes["sw.namespace"] == "sw.events.inframon.k8s.manifests" or attributes["sw.event.action"] == "k8s.pod.created"
            type: Contains
            source_entity: KubernetesPod
            destination_entity: KubernetesPod
            attributes:

service:
  # extensions: [solarwinds]
  # extensions: [file_storage/snapshots]
  pipelines:
    metrics/in:
      receivers: [otlp]
      exporters: [solarwindsentity]
    logs/in:
      receivers: [otlp]
      exporters: [solarwindsentity]

    logs/out:
      receivers: [solarwindsentity]
      exporters: [file, debug]