receivers:
  snowflake:
    username: # Required secret
    password: # Required secret
    account: # Required parameter
    warehouse: # Required parameter
    collection_interval: # Required parameter
    # schema: # Optional parameter
    # database: # Optional parameter
    # role: # Optional parameter
    metrics:
      snowflake.database.bytes_scanned.avg:
        enabled: true
      snowflake.database.query.count:
        enabled: true
      snowflake.query.blocked:
        enabled: true
      snowflake.query.bytes_deleted.avg:
        enabled: true
      snowflake.query.bytes_written.avg:
        enabled: true
      snowflake.query.compilation_time.avg:
        enabled: true
      snowflake.query.executed:
        enabled: true
      snowflake.query.execution_time.avg:
        enabled: true
      snowflake.query.queued_overload:
        enabled: true
      snowflake.query.queued_provision:
        enabled: true
      snowflake.queued_overload_time.avg:
        enabled: true
      snowflake.queued_provisioning_time.avg:
        enabled: true
      snowflake.queued_repair_time.avg:
        enabled: true
      snowflake.storage.stage_bytes.total:
        enabled: true
      snowflake.storage.storage_bytes.total:
        enabled: true
      snowflake.total_elapsed_time.avg:
        enabled: true
      snowflake.billing.cloud_service.total:
        enabled: true
      snowflake.billing.total_credit.total:
        enabled: true
      snowflake.billing.virtual_warehouse.total:
        enabled: true
      snowflake.billing.warehouse.cloud_service.total:
        enabled: true
      snowflake.billing.warehouse.total_credit.total:
        enabled: true
      snowflake.billing.warehouse.virtual_warehouse.total:
        enabled: true
      snowflake.logins.total:
        enabled: true
      snowflake.pipe.credits_used.total:
        enabled: true
      snowflake.query.bytes_spilled.local.avg:
        enabled: true
      snowflake.query.bytes_spilled.remote.avg:
        enabled: true
      snowflake.query.data_scanned_cache.avg:
        enabled: true
      snowflake.query.partitions_scanned.avg:
        enabled: true
      snowflake.rows_deleted.avg:
        enabled: true
      snowflake.rows_inserted.avg:
        enabled: true
      snowflake.rows_produced.avg:
        enabled: true
      snowflake.rows_unloaded.avg:
        enabled: true
      snowflake.rows_updated.avg:
        enabled: true
      snowflake.session_id.count:
        enabled: true
      snowflake.storage.failsafe_bytes.total:
        enabled: true

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30
  resource/snowflake:
    attributes:
      - key: sw.otelcol.receiver.name
        value: "snowflake"
        action: insert
      - key: sw.otelcol.integration.id
        value: # Required parameter
        action: insert
  resourcedetection/ec2:
    detectors: ["ec2"]
    timeout: 2s
    override: true
  resourcedetection/azure:
    detectors: ["azure"]
    timeout: 2s
    override: true
  resourcedetection/gcp:
    detectors: ["gcp"]
    timeout: 2s
    override: true
  resourcedetection/system:
    detectors: ["system"]
    timeout: 2s
    override: false
    system:
      hostname_sources: ["os"]
  batch:
    send_batch_max_size: 20000

extensions:
  solarwinds:
    token: # Required secret
    collector_name: # Required parameter
    data_center: # Required parameter

exporters:
  solarwinds:

service:
  extensions:
    - solarwinds
  pipelines:
    metrics/snowflake:
      receivers:
        - snowflake
      processors:
        - memory_limiter
        - resource/snowflake
        - resourcedetection/ec2
        - resourcedetection/azure
        - resourcedetection/gcp
        - resourcedetection/system
        - batch
      exporters:
        - solarwinds
