dist:
  module: github.com/solarwinds/solarwinds-otel-collector/k8s
  name: solarwinds-otel-collector-k8s
  description: SolarWinds OpenTelemetry Collector for Kubernetes
  version: 0.136.2
  output_path: ./_build

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/k8sobserver v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.136.0
  # Public SolarWinds contrib
  - gomod: github.com/solarwinds/solarwinds-otel-collector-contrib/extension/solarwindsextension v0.136.2

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.136.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.136.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.136.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.136.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatocumulativeprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/deltatorateprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/logdedupprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricsgenerationprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.136.0
  # Public SolarWinds contrib
  - gomod: github.com/solarwinds/solarwinds-otel-collector-contrib/processor/k8seventgenerationprocessor v0.136.2
  - gomod: github.com/solarwinds/solarwinds-otel-collector-contrib/processor/solarwindsprocessor v0.136.2
  - gomod: github.com/solarwinds/solarwinds-otel-collector-contrib/processor/swok8sworkloadtypeprocessor v0.136.2
  - gomod: github.com/solarwinds/solarwinds-otel-collector-contrib/processor/swok8sworkloadstatusprocessor v0.136.2

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/journaldreceiver v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8seventsreceiver v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sobjectsreceiver v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/receivercreator v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/simpleprometheusreceiver v0.136.0
  # Public SolarWinds contrib
  - gomod: github.com/solarwinds/solarwinds-otel-collector-contrib/receiver/swok8sdiscovery v0.136.2
  - gomod: github.com/solarwinds/solarwinds-otel-collector-contrib/receiver/swok8sobjectsreceiver v0.136.2

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.136.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/routingconnector v0.136.0
  # Public SolarWinds contrib
  - gomod: github.com/solarwinds/solarwinds-otel-collector-contrib/connector/solarwindsentityconnector v0.136.2

replaces:
  # k8sattributesprocessor@v0.131.0 is not compatible with v0.33.4
  - k8s.io/client-go v0.33.4 => k8s.io/client-go v0.32.3