name: Bug report
description: Create a report to help us improve
labels: ["bug", "needs triage"]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please make sure to fill out the entire form below, providing as much context as you can in order to help us triage and track down your bug as quickly as possible.

        Before filing a bug, please make sure you have searched through [existing bugs](https://github.com/solarwinds/solarwinds-otel-collector-releases/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug) to see if an existing issue covers your bug.
  - type: textarea
    attributes:
      label: Description
      description: Please describe in detail what the issue is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide sequence of steps to reproduce the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Result
      description: What is the expected result when the steps are reproduced?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Result
      description: What actually happens when the steps are reproduced?
    validations:
      required: true
  - type: input
    attributes:
      label: SolarWinds OpenTelemetry Collector version
      description: What version did you use? (e.g., `v0.113.0`)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment information
      description: Please provide any additional information about your installation.
      value: |
        ## Environment
        OS: (e.g., "Ubuntu 20.04")
        Compiler(if manually compiled): (e.g., "go 14.2")

  - type: textarea
    attributes:
      label: SolarWinds OpenTelemetry Collector configuration
      description: Please provide the configuration you are using (e.g. the YAML config file).
      placeholder: | # Empty Collector config
        receivers:
        exporters:
        processors:
        extensions:
        service:
          pipelines:
            traces:
              receivers: []
              exporters: []
              connectors: []
              processors: []
            metrics:
              receivers: []
              exporters: []
              connectors: []
              processors: []
            logs:
              receivers: []
              exporters: []
              connectors: []
              processors: []
      render: yaml
  - type: textarea
    attributes:
      label: Log output
      description: |
        Please copy and paste any relevant log output.
      render: shell
  - type: textarea
    attributes:
      label: Additional context
      description: Any additional information you think may be relevant to this issue.
