version: 2
project_name: solarwinds-otel-collector-releases
env:
  - COSIGN_YES=true
  - LD_FLAGS=-s -w
  - BUILD_FLAGS=-trimpath
  - CGO_ENABLED=0
release:
  replace_existing_artifacts: true
builds:
  - id: full
    goos:
      - linux
    goarch:
      - amd64
    dir: ../../cmd/solarwinds-otel-collector
    binary: solarwinds-otel-collector
    ldflags:
      - '{{ .Env.LD_FLAGS }}'
    flags:
      - '{{ .Env.BUILD_FLAGS }}'
      - -tags=full
archives:
  - id: full
    ids:
      - full
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    files:
      - LICENSE
checksum:
  name_template: '{{ .ProjectName }}_full_checksums.txt'
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    extra_files:
      - LICENSE
    image_templates:
      - solarwinds/solarwinds-otel-collector:{{ .Version }}-amd64
      - solarwinds/solarwinds-otel-collector:latest-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      # TODO: License? For all.
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
docker_manifests:
  - name_template: solarwinds/solarwinds-otel-collector:{{ .Version }}
    image_templates:
      - solarwinds/solarwinds-otel-collector:{{ .Version }}-amd64
  - name_template: solarwinds/solarwinds-otel-collector:latest
    image_templates:
      - solarwinds/solarwinds-otel-collector:latest-amd64
signs:
  - cmd: cosign
    args:
      - sign-blob
      - --output-signature
      - ${artifact}.sig
      - --output-certificate
      - ${artifact}.pem
      - ${artifact}
    signature: ${artifact}.sig
    artifacts: all
    certificate: ${artifact}.pem
docker_signs:
  - args:
      - sign
      - ${artifact}
    artifacts: all
sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
#monorepo:
#  tag_prefix: v
#partial:
#  by: target