// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/scraper/scrapertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := scrapertest.NewNopSettings()
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0

			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSwoAssetInstalledsoftwareDataPoint(ts, 1, "installedsoftware.date-val", "installedsoftware.name-val", "installedsoftware.publisher-val", "installedsoftware.version-val")

			allMetricsCount++
			mb.RecordSwoAssetInstalledupdatesDataPoint(ts, 1, "installedupdate.caption-val", "installedupdate.description-val", "installedupdate.hotfixid-val", "installedupdate.installedby-val", "installedupdate.installedon-val")

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			assert.Equal(t, 1, metrics.ResourceMetrics().Len())
			rm := metrics.ResourceMetrics().At(0)
			assert.Equal(t, res, rm.Resource())
			assert.Equal(t, 1, rm.ScopeMetrics().Len())
			ms := rm.ScopeMetrics().At(0).Metrics()
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, ms.Len())
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, ms.Len())
			}
			validatedMetrics := make(map[string]bool)
			for i := 0; i < ms.Len(); i++ {
				switch ms.At(i).Name() {
				case "swo.asset.installedsoftware":
					assert.False(t, validatedMetrics["swo.asset.installedsoftware"], "Found a duplicate in the metrics slice: swo.asset.installedsoftware")
					validatedMetrics["swo.asset.installedsoftware"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Currently installed software.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("installedsoftware.date")
					assert.True(t, ok)
					assert.EqualValues(t, "installedsoftware.date-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("installedsoftware.name")
					assert.True(t, ok)
					assert.EqualValues(t, "installedsoftware.name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("installedsoftware.publisher")
					assert.True(t, ok)
					assert.EqualValues(t, "installedsoftware.publisher-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("installedsoftware.version")
					assert.True(t, ok)
					assert.EqualValues(t, "installedsoftware.version-val", attrVal.Str())
				case "swo.asset.installedupdates":
					assert.False(t, validatedMetrics["swo.asset.installedupdates"], "Found a duplicate in the metrics slice: swo.asset.installedupdates")
					validatedMetrics["swo.asset.installedupdates"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Currently installed OS updates.", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("installedupdate.caption")
					assert.True(t, ok)
					assert.EqualValues(t, "installedupdate.caption-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("installedupdate.description")
					assert.True(t, ok)
					assert.EqualValues(t, "installedupdate.description-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("installedupdate.hotfixid")
					assert.True(t, ok)
					assert.EqualValues(t, "installedupdate.hotfixid-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("installedupdate.installedby")
					assert.True(t, ok)
					assert.EqualValues(t, "installedupdate.installedby-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("installedupdate.installedon")
					assert.True(t, ok)
					assert.EqualValues(t, "installedupdate.installedon-val", attrVal.Str())
				}
			}
		})
	}
}
