// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("solarwinds")
	ScopeName = "github.com/solarwinds/solarwinds-otel-collector/extension/solarwindsextension"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
