name: Docker scout scan
description: Comparison of Docker images using Docker Scout

inputs:
  username:
    description: Username for logging into the Docker Scout
    required: true
  token:
    description: PAT token for logging into the Docker Scout
    required: true
  current-image:
    description: Image to be compared
    required: true
  current-tag:
    description: Tag of the image to be compared
    required: true
  compare-to-image:
    description: Image name to compare to
    required: true
  compare-to-tag:
    description: Tag to compare to.
    required: true

runs:
  using: composite
  steps:
    - name: Ensure `compare-to-tag` is provided
      if: ${{ !inputs.compare-to-tag }}
      shell: bash
      run: exit 1

    - name: Log into registry with PAT to use SCOUT.
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Docker scout
      id: docker-scout
      uses: docker/scout-action@v1
      with:
        command: compare
        image: ${{ inputs.current-image }}:${{ inputs.current-tag }}
        to: ${{ inputs.compare-to-image }}:${{ inputs.compare-to-tag }}
        write-comment: false
