receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

extensions:
  solarwinds:
    token: v9KldJhYx2MCSqMQJ0wZQWFBSPAHwnUBrftfah4GcM5lP-fxTUQBmA2BglXH6KsYyhjWkYY
    collector_name: DEMO-TEST
    endpoint_url_override: otel.collector.na-02.dev-ssp.solarwinds.com:443
    without_entity: false

exporters:
  solarwinds:
  debug:
  file:
    path: result.log

connectors:
  solarwindsentity:
    source_prefix: "source."
    destination_prefix: "dest."
    schema:
      entities:
        - entity: KubernetesNamespace
          id:
            - k8s.namespace.name
            - sw.k8s.cluster.uid
          attributes:
        - entity: KubernetesCluster
          attributes:
            - k8s.cluster.name
          id:
            - sw.k8s.cluster.uid
        - entity: KubernetesPod
          id:
            - k8s.pod.name
            - sw.k8s.cluster.uid
          attributes:
            - k8s.namespace.name
      events:
        relationships:
          - type: MemberOf
            source_entity: KubernetesCluster
            destination_entity: KubernetesNamespace
            attributes:
          - type: CommunicatesWith
            source_entity: KubernetesPod
            destination_entity: KubernetesPod
            attributes:


service:
  extensions: [solarwinds]
  pipelines:
    metrics/in:
      receivers: [otlp]
      exporters: [solarwindsentity]
    logs/in:
      receivers: [otlp]
      exporters: [solarwindsentity]

    logs/out:
      receivers: [solarwindsentity]
      exporters: [file, debug]
