name: Reusable CI workflow

on:
  workflow_call:
    inputs:
      distribution:
        required: true
        type: string
      goos:
        required: true
        type: string
      goarch:
        required: true
        type: string
      config_suffix:
        required: false
        type: string
      runner_os:
        required: false
        type: string
        default: ubuntu-24.04

env:
  GORELEASER_VERSION: v2.8.2

jobs:
  check-goreleaser:
    strategy:
      matrix:
        GOOS: ${{ fromJSON( inputs.goos )}}
        GOARCH: ${{ fromJSON( inputs.goarch )}}
        SUFFIX: ${{ fromJSON( inputs.config_suffix )}}
    runs-on: ${{ inputs.runner_os }}
    outputs:
      version: ${{ steps.prep.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          platforms: arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: "~1.24"
          check-latest: true

      - name: Run GoReleaser for ${{ inputs.distribution }} (linux)
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          distribution: goreleaser
          version: ${{ env.GORELEASER_VERSION }}
          workdir: distributions/${{ inputs.distribution }}
          args: --snapshot --clean --skip=sign,sbom --timeout 2h --config .goreleaser-${{ matrix.GOOS}}-${{matrix.GOARCH}}${{matrix.SUFFIX}}.yaml # --split
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
          GOARM: "7" # Default is 6
          GOAMD64: v1 # TODO: required?

      # TODO: /**/file.json
      - name: Print built artifacts
        run: cat ./distributions/${{ inputs.distribution }}/dist/artifacts.json

      # TODO: /**/file.json
      - name: Print metadata
        run: cat ./distributions/${{ inputs.distribution }}/dist/metadata.json

      - name: Print dist folder contents
        if: always() # TODO: WHY?WHY?
        run: ls -laR ./distributions/${{ inputs.distribution }}/dist

      # TODO: /**/file.json
      - name: Prepare variables
        if: matrix.GOOS == 'linux'
        id: prep
        run: |
          # Find version number and types of built artifacts
          echo "version=$(cat ./distributions/${{ inputs.distribution }}/dist/metadata.json | jq -r '.version')" >> "$GITHUB_OUTPUT"
          echo "types=$(cat ./distributions/${{ inputs.distribution }}/dist/artifacts.json | jq '[.[].type]' | tr -d '\n' )" >> "$GITHUB_OUTPUT"
          
          # Find GOOS and GOARCH
          os=$(cat ./distributions/${{ inputs.distribution }}/dist/artifacts.json | jq -r '.[] | select(.name | contains(".tar.gz")) | .goos')
          arch=$(cat ./distributions/${{ inputs.distribution }}/dist/artifacts.json | jq -r '.[] | select(.name | contains(".tar.gz")) | .goarch')
          echo "arch=$os-$arch" >> "$GITHUB_OUTPUT"
          
          # Find binary path
          echo "binary-path=$(cat ./distributions/${{ inputs.distribution }}/dist/artifacts.json | jq -r 'map(select(any(.type; contains("Binary")))) | .[].path' )" >> "$GITHUB_OUTPUT"

      - name: Print version and target
        if: matrix.GOOS == 'linux'
        run: |
          echo 'Version: ${{ steps.prep.outputs.version }}'
          echo 'Types: ${{ steps.prep.outputs.types }}'
          echo 'Arch: ${{ steps.prep.outputs.arch }}'
          echo 'Images?: ${{ steps.prep.outputs.container-images }}'

      - name: Copy binary to distro root folder
        if: matrix.GOOS == 'linux'
        run: cp ./distributions/${{ inputs.distribution }}/${{ steps.prep.outputs.binary-path }} ./distributions/${{ inputs.distribution }}

      - name: Build container images locally
        if: matrix.GOOS == 'linux' && contains(steps.prep.outputs.types, 'Docker Image')
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: ./distributions/${{ inputs.distribution }}
          push: false
          load: true
          tags: ${{ inputs.distribution }}:${{ steps.prep.outputs.version }}-${{ steps.prep.outputs.arch }}

      - name: Export container image to tarball
        if: matrix.GOOS == 'linux' && contains(steps.prep.outputs.types, 'Docker Image')
        run: |
          docker save ${{ inputs.distribution }}:${{ steps.prep.outputs.version }}-${{ steps.prep.outputs.arch }} > /tmp/${{ inputs.distribution }}.tar

      - name: Upload container image artifact
        if: matrix.GOOS == 'linux' && contains(steps.prep.outputs.types, 'Docker Image')
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ inputs.distribution }}-image-${{ steps.prep.outputs.version }}-${{ steps.prep.outputs.arch }}
          path: /tmp/${{ inputs.distribution }}.tar
          retention-days: 7

  docker-tests:
    needs:
      - check-goreleaser
    strategy:
      matrix:
        GOOS: ${{ fromJSON( inputs.goos) }}
        GOARCH: ${{ fromJSON( inputs.goarch) }}
        exclude:
          - GOOS: windows
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          platforms: arm64

      - name: Download container image artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: ${{ inputs.distribution }}-image-${{ needs.check-goreleaser.outputs.version }}-${{ matrix.GOOS }}-${{ matrix.GOARCH }}

      - name: Load image into docker
        run: |
          docker image load --input ./${{ inputs.distribution }}.tar
          docker image ls
          docker image inspect ${{ inputs.distribution }}:${{ needs.check-goreleaser.outputs.version }}-${{ matrix.GOOS }}-${{ matrix.GOARCH }}

      - name: Run container image
        run: |
          echo "Running container..."
          docker run --name ${{ inputs.distribution }} \
            -d \
            -v ${PWD}/tests/docker-tests/default-config.yaml:/config.yaml \
            ${{ inputs.distribution }}:${{ needs.check-goreleaser.outputs.version }}-${{ matrix.GOOS }}-${{ matrix.GOARCH }} \
            --config /config.yaml
          echo "docker ps:"
          echo ""
          docker ps
          echo "Sleeping for a bit..."
          sleep 10
          echo "Checking logs for correct startup..."
          docker logs ${{ inputs.distribution }} >& docker-logs-${{ inputs.distribution }}.log
          if cat docker-logs-${{ inputs.distribution }}.log | grep "Everything is ready."; then
            echo "${{ inputs.distribution }} started up correctly"
          else
            echo "${{ inputs.distribution }} failed to start"
            echo "Printing container logs below..."
            echo ""
            cat docker-logs-${{ inputs.distribution }}.log
            exit 1
          fi