name: CI - Full

on:
  # TODO: push to main, PR to main, consider merge group?
  push:

jobs:
  check-goreleaser:
    name: CI - Full
    uses: ./.github/workflows/base-ci.yml
    with:
      distribution: full
      goos: '[ "linux" ]'
      goarch: '[ "amd64", "arm64" ]'
    secrets: inherit

  check-goreleaser-windows:
    name: CI - Full
    uses: ./.github/workflows/base-ci.yml
    with:
      distribution: full
      goos: '[ "windows" ]'
      goarch: '[ "amd64" ]'
      runner_os: 'windows-2022'
    secrets: inherit
